# Generated by Django 4.1.1 on 2022-09-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('price', models.IntegerField()),
                ('indications', models.CharField(max_length=240)),
                ('againstIndications', models.CharField(max_length=240)),
                ('adverseReactions', models.CharField(max_length=240)),
                ('precautions', models.CharField(max_length=240)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
